//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinTemplate.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinTemplate.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Gallery Example.
        /// </summary>
        internal static string Action_Show_Gallery {
            get {
                return ResourceManager.GetString("Action_Show_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Language Example.
        /// </summary>
        internal static string Action_Show_Language {
            get {
                return ResourceManager.GetString("Action_Show_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Messaging Example.
        /// </summary>
        internal static string Action_Show_Messaging {
            get {
                return ResourceManager.GetString("Action_Show_Messaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have lost your connection. Try again..
        /// </summary>
        internal static string Error_Connection_Lost {
            get {
                return ResourceManager.GetString("Error_Connection_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access to internet.
        /// </summary>
        internal static string Error_Connection_None {
            get {
                return ResourceManager.GetString("Error_Connection_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred, please try again later..
        /// </summary>
        internal static string Error_Generic {
            get {
                return ResourceManager.GetString("Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Lang_EN {
            get {
                return ResourceManager.GetString("Lang_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string Lang_FR {
            get {
                return ResourceManager.GetString("Lang_FR", resourceCulture);
            }
        }
    }
}
